name: pmg
channels:
 - openbabel
 - conda-forge
 - matsci
dependencies:
 - python
 - pip
 - pymatgen
 - openbabel
 - ipywidgets==7.5.1
 - jupyter_contrib_nbextensions
 - fileupload
 - pip:
   - imolecule
   - ipyfilechooser
